### ISSUE TITLE
Can't write when Token = "--"

### ISSUE THREAD

**Issue by traumfresser** [korpling/pepperModules-PAULAModules#8]
```

javax.xml.stream.XMLStreamException: Illegal input: comment content has embedded -- in it (index 4)
        at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1564)
        at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1571)
        at com.ctc.wstx.sw.BaseStreamWriter.reportNwfContent(BaseStreamWriter.java:1617)
        at com.ctc.wstx.sw.BaseStreamWriter.writeComment(BaseStreamWriter.java:516)
        at org.corpus_tools.pepper.util.XMLStreamWriter.writeComment(XMLStreamWriter.java:170)
        at org.corpus_tools.peppermodules.paula.Salt2PAULAMapper.mapTokens(Salt2PAULAMapper.java:385)
        at org.corpus_tools.peppermodules.paula.Salt2PAULAMapper.mapSDocument(Salt2PAULAMapper.java:151)
        at org.corpus_tools.pepper.impl.PepperMapperControllerImpl.map(PepperMapperControllerImpl.java:246)
        at org.corpus_tools.pepper.impl.PepperMapperControllerImpl.run(PepperMapperControllerImpl.java:184)
Cannot map 'salt:/0/KAJUK/Soeldnerleben' with module 'PAULAExporter', because of a mapping result was 'FAILED'.
An exception was thrown by the mapper threads 'Thread[PAULAExporter_mapper(salt:/KAJUK/Soeldnerleben),5,PAULAExporter_map
perGroup]'.
org.corpus_tools.pepper.modules.exceptions.PepperModuleException: A data error occured for Pepper mapper 'org.corpus_tool
s.peppermodules.paula.Salt2PAULAMapper'. Could write document salt:/KAJUK/Soeldnerleben to path file:/D:/Pepper_2015.12.2
2/pepper/./plugins/org.corpus-tools.pepperModules-PAULAModules_1.2.0/
        at org.corpus_tools.peppermodules.paula.Salt2PAULAMapper.mapSDocument(Salt2PAULAMapper.java:158)
        at org.corpus_tools.pepper.impl.PepperMapperControllerImpl.map(PepperMapperControllerImpl.java:246)
        at org.corpus_tools.pepper.impl.PepperMapperControllerImpl.run(PepperMapperControllerImpl.java:184)
Caused by: org.corpus_tools.pepper.modules.exceptions.PepperModuleException: A data error occured for Pepper mapper 'org.
corpus_tools.peppermodules.paula.Salt2PAULAMapper'. Cannot write in file 'D:\Korpora\KAJUK_SaltXML\PAULA\KAJUK\Soeldnerle
ben\Soeldnerleben.tok.xml', because of a nested exception.
        at org.corpus_tools.peppermodules.paula.Salt2PAULAMapper.mapTokens(Salt2PAULAMapper.java:395)
        at org.corpus_tools.peppermodules.paula.Salt2PAULAMapper.mapSDocument(Salt2PAULAMapper.java:151)
        ... 2 more
Caused by: javax.xml.stream.XMLStreamException: Illegal input: comment content has embedded -- in it (index 4)
        at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1564)
        at com.ctc.wstx.sw.BaseStreamWriter.throwOutputError(BaseStreamWriter.java:1571)
        at com.ctc.wstx.sw.BaseStreamWriter.reportNwfContent(BaseStreamWriter.java:1617)
        at com.ctc.wstx.sw.BaseStreamWriter.writeComment(BaseStreamWriter.java:516)
        at org.corpus_tools.pepper.util.XMLStreamWriter.writeComment(XMLStreamWriter.java:170)
        at org.corpus_tools.peppermodules.paula.Salt2PAULAMapper.mapTokens(Salt2PAULAMapper.java:385)
        ... 3 more


```
Data and workflow description: https://box.hu-berlin.de/f/3ad60b137e/

**Comment by FlorianZipser** [comment]
It seems, you triggered a funny bug, which does not allow to have tokens including the text "--". We need to solve this.
@us:
When the exporter export the tokens, it also prints the overlapped text in comments above the token-line. If the token text contains "--", the xml writer denies to write it since, these characters are not allowed as part of xml comments.

**Comment by thomaskrause** [comment]
This was fixed in the newest release of the PAULA module. Please execute
```
pepperStart.bat update all
```
to get this new version in your pepper installation.
